#This is the Base Docker image for development on the Ubuntu

#Choose the Base Image
FROM ubuntu:14.04

#Describe the maintainer
MAINTAINER Kumar Saurabh Sinha <sinha.ksaurabh@gmail.com>

#Update the Repository List
RUN apt-get update

#Install the Requirements
RUN apt-get -y install vim
RUN apt-get -y install screen


